### PR TITLE
Fix for issue: No merchantid #11. (take 2)

### PR DESCRIPTION
**Pull request by noud**
hi Robin and Barry,

i did redo my pull request leaving out the package name change.

is it okay to pull-up now?

it is a fix for issue #11, No merchantid.
I did get the same issue and this fixes it adding a html header.

thanks,
Noud

### CODE REVIEW

**Comment by barryvdh** [comment]
Can you fix the coding style issues?

**Comment by noud** [comment]
hi Barry,
i fixed the PSR2 issues.
Is it okay now?
Thanks,
Noud

**Comment by robinvalk** [comment]
Thanks @noud!

**Comment by noud** [comment]
you are welcome Robin.

could also please update it's packagist page.
after the merge and after removing my github repo from composer.json, i did:

root@3f79befa4ab9:/var/www/wdt# composer require fruitcakestudio/omnipay-sisow:"master-dev"
Do not run Composer as root/super user! See https://getcomposer.org/root for details
./composer.json has been updated                                                    
Loading composer repositories with package information
Updating dependencies (including require-dev)                      
Package operations: 1 install, 0 updates, 0 removals
  - Installing fruitcakestudio/omnipay-sisow (dev-master 3e257c5): Cloning 3e257c5670 from cache

So i still get the commit before my pull request merge.
and the packagist page still shows:

dev-master / 3.0.x-dev 2018-05-15 08:32 UTC

Thanks,
Noud

**Comment by robinvalk** [comment]
Sorry, it took a little while, the new version is now tagged. Thanks for contributing!

**Comment by noud** [comment]
Okay it is tagged but
https://packagist.org/packages/fruitcakestudio/omnipay-sisow#dev-master
still shows:
dev-master / 3.0.x-dev 2018-05-15 08:32 UTC

could you also please update it's packagist page.

**Comment by robinvalk** [comment]
Should be ok now, didn't come through automatically.

**Pull request merged**
